server:
  port: 80
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    url: jdbc:mysql://localhost:3306/goguma?serverTimeZone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: asd1234
  devtools:
    restart:
      enabled: true

#  datasource:
#    url: jdbc:mysql://13.211.47.78/goguma?serverTimeZone=Asia/Seoul
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: Sa1953vb!
#  devtools:
#    restart:
#      enabled: true


#  sql:
#    init: # 초기 sql 파일 읽기
#      mode: never #  always : 서버 실행시마다 data, schema 읽음, never : 읽지 않음
##      이부분은 gradle implementation h2 일때만 사용
#      schema-locations: # 스키마 (테이블 생성 등)
#        - classpath:schema.sql
#      data-locations: # 샘플 데이터
#        - classpath:data.sql
 
mybatis:
  mapper-locations:
  - classpath:mapper/**.xml 
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    
logging:
  level:
    org:
    mybatis: DEBUG
    hibernate: info
